using System.Runtime.InteropServices;

namespace NativeAotLib.Core;

public class NativeEntryPoint
{
    [UnmanagedCallersOnly(EntryPoint = "aotsample_add")]
    public static int Add(int a, int b)
    {
        return a + b;
    }

    [UnmanagedCallersOnly(EntryPoint = "aotsample_write_line")]
    public static int WriteLine(IntPtr pString)
    {
        // The marshalling code is typically auto-generated by a custom tool in larger projects.
        try
        {
            // UnmanagedCallersOnly methods only accept primitive arguments. The primitive arguments
            // have to be marshalled manually if necessary.
            var str = Marshal.PtrToStringAnsi(pString);
            if (string.IsNullOrEmpty(str))
            {
                throw new ArgumentNullException(nameof(pString));
            }
            Console.WriteLine(str);
        }
        catch
        {
            // Exceptions escaping out of UnmanagedCallersOnly methods are treated as unhandled exceptions.
            // The errors have to be marshalled manually if necessary.
            return -1;
        }
        return 0;
    }

    [UnmanagedCallersOnly(EntryPoint = "aotsample_sumstring")]
    public static IntPtr SumString(IntPtr first, IntPtr second)
    {
        try
        {
            // Parse strings from the passed pointers 
            var my1String = Marshal.PtrToStringAnsi(first);
            var my2String = Marshal.PtrToStringAnsi(second);
            if (string.IsNullOrEmpty(my1String))
            {
                throw new ArgumentNullException(nameof(first));
            }
            if (string.IsNullOrEmpty(my2String))
            {
                throw new ArgumentNullException(nameof(second));
            }

            // Concatenate strings 
            string sum = $"{my1String}{my2String}";
            IntPtr sumPointer = Marshal.StringToHGlobalAnsi(sum);
            return sumPointer;
        }
        catch
        {
            return IntPtr.Zero;
        }
    }
}
